# IntelliJ Platform Artifacts Repositories
# https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

# IntelliJ Platform version
platformVersion=2024.3

# Plugin Dependencies
# https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html
platformPlugins=

# Gradle version
gradleVersion=8.11.1

# Plugin version
pluginGroup=com.equadon.intellij.mips
pluginName=MIPS
pluginVersion=0.1

# Plugin build number range
# See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
pluginSinceBuild=243
pluginUntilBuild=243.*

# JVM configuration
org.gradle.jvmargs=-Xmx2048m -XX:+UseG1GC
